#!/usr/bin/env node
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";

const DEFAULT_OUT = "deploy/agentrun/.generated/secrets.env";
const SECRET_KEYS = ["CODEX_GATEWAY_BEARER_TOKEN", "AGENTRUN_RUNTIME_API_KEY"];

function usage(exitCode = 0) {
  const stream = exitCode === 0 ? process.stdout : process.stderr;
  stream.write(`Usage:
  node deploy/agentrun/scripts/bootstrap_secrets.mjs [options]

Options:
  --out PATH          Output env file. Defaults to ${DEFAULT_OUT}.
  --force             Rotate generated values.
  --write-deepseek    Also write DEEPSEEK_API_KEY from the current environment.
  -h, --help          Show this help.

The output file is created with mode 0600 under deploy/agentrun/.generated/,
which is ignored by git. Secret values are never printed.
`);
  process.exit(exitCode);
}

function parseArgs(argv) {
  const opts = { out: DEFAULT_OUT, force: false, writeDeepSeek: false };
  for (let i = 0; i < argv.length; i += 1) {
    const arg = argv[i];
    if (arg === "-h" || arg === "--help") usage(0);
    if (arg === "--out") {
      opts.out = argv[++i];
    } else if (arg === "--force") {
      opts.force = true;
    } else if (arg === "--write-deepseek") {
      opts.writeDeepSeek = true;
    } else {
      throw new Error(`unknown argument: ${arg}`);
    }
  }
  return opts;
}

function parseEnvFile(file) {
  const values = new Map();
  if (!fs.existsSync(file)) return values;
  const raw = fs.readFileSync(file, "utf8");
  for (const line of raw.split(/\r?\n/)) {
    const match = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (!match) continue;
    values.set(match[1], match[2]);
  }
  return values;
}

function randomSecret(prefix) {
  return `${prefix}_${crypto.randomBytes(32).toString("base64url")}`;
}

function main() {
  const opts = parseArgs(process.argv.slice(2));
  const values = parseEnvFile(opts.out);
  for (const key of SECRET_KEYS) {
    if (opts.force || !values.get(key)) {
      const prefix = key === "AGENTRUN_RUNTIME_API_KEY" ? "ar" : "gw";
      values.set(key, randomSecret(prefix));
    }
  }
  if (opts.writeDeepSeek) {
    if (!process.env.DEEPSEEK_API_KEY) {
      throw new Error("DEEPSEEK_API_KEY is not set; cannot write it");
    }
    values.set("DEEPSEEK_API_KEY", process.env.DEEPSEEK_API_KEY);
  }

  fs.mkdirSync(path.dirname(opts.out), { recursive: true });
  const body = [
    "# Generated by deploy/agentrun/scripts/bootstrap_secrets.mjs.",
    "# Do not commit this file.",
    ...[...values.entries()].map(([key, value]) => `${key}=${value}`),
    "",
  ].join("\n");
  fs.writeFileSync(opts.out, body, { mode: 0o600 });
  fs.chmodSync(opts.out, 0o600);
  process.stdout.write(`ok: wrote ${opts.out} with keys ${[...values.keys()].join(", ")}\n`);
}

try {
  main();
} catch (error) {
  process.stderr.write(`error: ${error.message}\n`);
  process.exit(1);
}
